TRUNCATE TABLE KOSYAK1998YANDEXRU__STAGING.{sql_key};

COPY KOSYAK1998YANDEXRU__STAGING.{sql_key}({sql_parameters})
FROM LOCAL '/data/{sql_key}.csv'
DELIMITER ','
REJECTED DATA AS TABLE KOSYAK1998YANDEXRU__STAGING.{sql_key}_rej;