import vertica_python
from pathlib import Path
from logging import Logger

CONN_INFO = {'host': '51.250.75.20',
             'port': 5433,
             'user': 'KOSYAK1998YANDEXRU',
             'password': 'eTxHgF49CopW9TQ',
             'database': 'dwh',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # autocommit is off by default
             'autocommit': False,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             # 5 seconds timeout for a socket operation (Establishing a TCP connection or read/write operation)
             'connection_timeout': 30}

def vertica_operator(path_to_script: str, log: Logger) -> None:
    script = Path(path_to_script).read_text()
    log.info("Prepared script to execute:")
    log.info(script)    
    with vertica_python.connect(**CONN_INFO) as connection:
        log.info("Vertica connection succses")
        cur = connection.cursor()
        cur.execute(script)
        log.info(f"Vertica: data has been uploaded succsesfully")
        connection.commit()